### ISSUE TITLE
config.decoder_start_token_id issue

### ISSUE THREAD

**Issue by jeetendraabvv** [ashokurlana/Indian-Language-Summarization#1]
try to run the command:
!python run_summarization.py \
    --model_name_or_path ai4bharat/IndicBART \
    --text_column Full_Text \
    --summary_column Short_Summury \
    --do_train \
    --do_eval \
    --do_predict \
    --lang hi_IN \
    --train_file train.csv \
    --validation_file dev.csv \
    --test_file test.csv \
    --max_source_length 1024 \
    --max_target_length 256 \
    --val_max_target_length 256 \
    --output_dir ./tmp/outputs/ \
    --per_device_train_batch_size=1 \
    --per_device_eval_batch_size=1 \
    --dataloader_num_workers 4 \
    --logging_strategy "epoch" \
    --save_strategy "no" \
    --fp16 True \
    --overwrite_output_dir \
    --predict_with_generate \
    --num_train_epochs 1 

But getting the following Error:

Downloading pytorch_model.bin: 100%|##########| 976M/976M [03:09<00:00, 5.17MB/s]
Downloading pytorch_model.bin: 100%|##########| 976M/976M [03:09<00:00, 5.15MB/s]
[INFO|modeling_utils.py:2275] 2023-08-01 21:39:57,567 >> loading weights file pytorch_model.bin from cache at C:\Users\Administrator/.cache\huggingface\hub\models--ai4bharat--IndicBART\snapshots\78466a0c0e29f9229f7005623ecd6bc4243c0ae0\pytorch_model.bin
[INFO|configuration_utils.py:543] 2023-08-01 21:39:58,010 >> Generate config GenerationConfig {
  "bos_token_id": 64000,
  "eos_token_id": 64001,
  "forced_eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.26.1"
}

[INFO|modeling_utils.py:2860] 2023-08-01 21:40:00,197 >> All model checkpoint weights were used when initializing MBartForConditionalGeneration.

[INFO|modeling_utils.py:2868] 2023-08-01 21:40:00,197 >> All the weights of MBartForConditionalGeneration were initialized from the model checkpoint at ai4bharat/IndicBART.
If your task is similar to the task the model of the checkpoint was trained on, you can already use MBartForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2522] 2023-08-01 21:40:00,481 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "C:\Users\Administrator\sample\Indian-Language-Summarization-main\run_summarization.py", line 705, in <module>
    main()
  File "C:\Users\Administrator\sample\Indian-Language-Summarization-main\run_summarization.py", line 405, in main
    raise ValueError("Make sure that `config.decoder_start_token_id` is correctly defined")
ValueError: Make sure that `config.decoder_start_token_id` is correctly defined

**Comment by ashokurlana** [comment]
In run_summarization.py replace the line 404 with the following line
```
model.config.decoder_start_token_id = tokenizer._convert_token_to_id_with_added_voc("<s>")
```
The run the following command
```
!python run_summarization.py
--model_name_or_path ai4bharat/IndicBARTSS
--text_column Full_Text
--summary_column Short_Summury
--do_train
--do_eval
--do_predict
--train_file train.csv
--validation_file dev.csv
--test_file test.csv
--max_source_length 1024
--max_target_length 256
--val_max_target_length 256
--output_dir ./tmp/outputs/
--per_device_train_batch_size=1
--per_device_eval_batch_size=1
--dataloader_num_workers 4
--logging_strategy "epoch"
--save_strategy "no"
--overwrite_output_dir
--predict_with_generate
--forced_bos_token=tokenizer.lang_code_to_id["hi_IN"] \
--num_train_epochs 1
```
